[package]
name = "picmash"
default-run = "picmash"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
autobins = false
description = "Native local-image preference chamber"

[[bin]]
name = "picmash"
path = "src/main.rs"

[features]
egui-test = ["eternalist-apps/egui-test"]

[dependencies]
anyhow = "1.0.104"
arboard = "3.6.1"
atomic-write-file = "0.3.1"
base64 = "0.23.1"
blake3 = "1.8.7"
brass_poolrooms = "0.15.0"
crossbeam-channel = "0.5.16"
egui = "=0.36.1"
eternalist-apps = "0.12.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
jxl-oxide = { version = "0.12.6", features = ["image"] }
md5 = "0.8.1"
picmash-contract = { path = "../picmash-contract" }
picmash-engine = { path = "../picmash-engine" }
pollster = "1.0.1"
rusqlite = { version = "0.40.2", features = ["bundled"] }
rfd = { version = "0.17.2", default-features = false, features = ["xdg-portal"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.5"
tempfile = "3.27.0"
ureq = { version = "3.4.0", default-features = false, features = ["native-tls"] }
walkdir = "2.5.0"
wait-timeout = "0.2.1"

[lints]
workspace = true

[dev-dependencies]
proptest = "1.11.0"
