name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

jobs:
  foundry:
    name: Foundry
    permissions:
      contents: read
    uses: aoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoa/eternalist-foundry/.github/workflows/pipeline.yml@31a3e4e6b317446544294df3607d333c8a9296a3

  publish:
    name: Publish
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: foundry
    permissions:
      contents: write
    uses: aoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoaoa/eternalist-foundry/.github/workflows/publish.yml@31a3e4e6b317446544294df3607d333c8a9296a3
