use crate::{
    model::LATENT_DIM,
    quality_features::{TECHNICAL_PRIOR_ARTIFACT_KEY, VIBE_DESCRIPTOR_DIM},
};

pub const ACTIVE_QUALITY_MODEL_SLOT: &str = "active";
pub const DEFAULT_QUALITY_PRIOR_FAMILY: &str = "perturbative-linear";
pub const DEFAULT_QUALITY_PRIOR_REVISION: &str = "bootstrap";
pub const LEGACY_HEART_GLOBAL_BOOST: f32 = 0.18;
pub const LEGACY_HEART_SESSION_BOOST: f32 = 0.32;
pub const LEGACY_LR_DUEL_ALPHA: f32 = 0.05;
pub const LEGACY_LR_DUEL_COORD: f32 = 0.045;
pub const LEGACY_LR_DUEL_MOOD: f32 = 0.08;
pub const LEGACY_LR_DUEL_HEAD: f32 = 0.02;
pub const LEGACY_LR_NUDGE_ALPHA: f32 = 0.008;
pub const LEGACY_LR_NUDGE_COORD: f32 = 0.01;
pub const LEGACY_LR_NUDGE_MOOD: f32 = 0.045;
pub const LEGACY_LR_NUDGE_FRONTIER: f32 = 0.05;
pub const LEGACY_LR_NUDGE_OFFSET: f32 = 0.09;
pub const LEGACY_LR_NUDGE_HEAD: f32 = 0.05;
pub const LEGACY_L2_ALPHA: f32 = 0.0015;
pub const LEGACY_L2_COORD: f32 = 0.001;
pub const LEGACY_L2_MOOD: f32 = 0.02;
pub const LEGACY_L2_FRONTIER: f32 = 0.02;
pub const LEGACY_L2_OFFSET: f32 = 0.012;
pub const LEGACY_L2_SESSION_HEAD: f32 = 0.01;
pub const LEGACY_PRIOR_PULL: f32 = 0.015;
pub const LEGACY_PROJECTION_WEIGHT_DECAY: f32 = 0.0005;
pub const LEGACY_LR_PROJECTION: f32 = 0.006;
pub const LEGACY_LR_NUDGE_PROJECTION: f32 = LEGACY_LR_PROJECTION;
pub const LEGACY_EXACT_OFFSET_EPSILON: f32 = 0.0005;
pub const HIERARCHICAL_DUEL_BETA: f32 = 1.0;
pub const HIERARCHICAL_FACE_WEIGHT: f32 = 1.0;
pub const HIERARCHICAL_FACE_CENTER: f32 = 1500.0;
pub const HIERARCHICAL_FACE_SCALE: f32 = 350.0;
pub const HIERARCHICAL_TECH_WEIGHT: f32 = 0.7;
pub const HIERARCHICAL_BASELINE_PRIOR_VARIANCE: f32 = 1.0;
pub const HIERARCHICAL_LOADING_PRIOR_VARIANCE: f32 = 0.8;
pub const HIERARCHICAL_TECH_PRIOR_FLOOR: f32 = 0.45;
pub const HIERARCHICAL_VIBE_PRIOR_VARIANCE: f32 = 0.85;
pub const HIERARCHICAL_SESSION_MOOD_PRIOR_VARIANCE: f32 = 1.0;
pub const HIERARCHICAL_SESSION_VIBE_PRIOR_VARIANCE: f32 = 1.0;
pub const HIERARCHICAL_FRONTIER_PRIOR_VARIANCE: f32 = 1.0;
pub const HIERARCHICAL_MIN_VARIANCE: f32 = 1e-4;
pub const HIERARCHICAL_UNARY_REJECT_BETA: f32 = 1.65;
pub const HIERARCHICAL_UNARY_ACCEPT_BETA: f32 = 1.25;
pub const HIERARCHICAL_UNARY_HEART_BETA: f32 = 0.95;
pub const PERTURBATIVE_DIM: usize = LATENT_DIM + VIBE_DESCRIPTOR_DIM;
pub const PERTURBATIVE_SESSION_WEIGHT_PRIOR_VARIANCE: f32 = 0.12;
pub const PERTURBATIVE_SESSION_IMPORTANCE_RAW_PRIOR_MEAN: f32 = -2.2;
pub const PERTURBATIVE_SESSION_IMPORTANCE_RAW_PRIOR_VARIANCE: f32 = 0.18;
pub const PERTURBATIVE_THRESHOLD_CENTER: f32 = 0.0;
pub const PERTURBATIVE_THRESHOLD_PRIOR_VARIANCE: f32 = 0.28;
pub const PERTURBATIVE_VIBE_SCALE: f32 = 0.35;
pub const PERTURBATIVE_FACE_WEIGHT_REAL_DEFAULT: f32 = 1.0;
pub const PERTURBATIVE_FACE_WEIGHT_ANIME_DEFAULT: f32 = 1.0;
pub const PERTURBATIVE_TECH_WEIGHT_REAL_DEFAULT: f32 = 0.7;
pub const PERTURBATIVE_VIBE_SCALE_REAL_DEFAULT: f32 = PERTURBATIVE_VIBE_SCALE;

#[must_use]
pub const fn technical_prior_artifact_key() -> &'static str {
    TECHNICAL_PRIOR_ARTIFACT_KEY
}

#[must_use]
pub const fn perturbative_hyper_artifact_key() -> &'static str {
    "perturbative_hyper_v3"
}
